# Generated by Django 6.0.5 on 2026-06-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_itemvenda_produto_alter_venda_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
